"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Activity, Building2, ExternalLink, LogOut, Plus, ShieldCheck, Users, X } from "lucide-react";
import { clearPortalSession, getPortalSession, portalProfile, type PortalProfile, type PortalSession } from "@/lib/portal-auth";
const ssmaUrl = process.env.NEXT_PUBLIC_SSMA_APP_URL || "http://localhost:3000";
const pulsarUrl = process.env.NEXT_PUBLIC_PULSAR_APP_URL || "https://viver-pulsar.vdeolisantos.chatgpt.site";
export default function SistemaCliente() {
 const router=useRouter(),[session,setSession]=useState<PortalSession|null>(null),[profile,setProfile]=useState<PortalProfile|null>(null),[manager,setManager]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{const current=getPortalSession();if(!current){router.replace("/area-do-cliente");return}setSession(current);portalProfile(current.access_token).then(setProfile).catch(()=>{clearPortalSession();router.replace("/area-do-cliente")})},[router]);
 function logout(){clearPortalSession();router.replace("/area-do-cliente")}
 async function createClient(form:FormData){if(!session)return;setMessage("Cadastrando...");const response=await fetch("/api/clientes",{method:"POST",headers:{Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(Object.fromEntries(form))});const body=await response.json();setMessage(response.ok?"Cliente e usuário cadastrados com sucesso.":body.error||"Não foi possível cadastrar.");if(response.ok)(document.getElementById("client-form") as HTMLFormElement)?.reset()}
 if(!session)return <div className="portal-loading">Verificando seu acesso...</div>;
 return <div className="client-system-page"><header className="client-system-bar"><div><img src="/brand/logo-viver-cabecalho.webp" alt="Viver"/><span><b>Integra SSMA</b><small>Área do Cliente</small></span></div><nav>{profile?.role==="Administrador"&&<button onClick={()=>setManager(true)}><Users size={16}/> Cadastrar cliente</button>}<a className="client-app-option" href={pulsarUrl} target="_blank" rel="noreferrer"><Activity size={16}/> VIVER Pulsar</a><a href={ssmaUrl} target="_blank" rel="noreferrer"><ExternalLink size={16}/> Abrir Integra SSMA</a><button onClick={logout}><LogOut size={16}/> Sair</button></nav></header><div className="client-system-status"><span><ShieldCheck size={16}/> Acesso protegido</span><p>{profile?.name||profile?.email} · {profile?.role||"Carregando perfil"}</p></div><iframe className="client-system-frame" src={ssmaUrl} title="Sistema Integra SSMA" allow="clipboard-write"/>{manager&&<div className="client-manager-backdrop"><section className="client-manager"><header><div><span>ADMINISTRAÇÃO</span><h2>Novo cliente e usuário</h2></div><button onClick={()=>setManager(false)} aria-label="Fechar"><X/></button></header><form id="client-form" action={createClient}><label>Razão social / nome da empresa<input name="companyName" required/></label><label>CNPJ<input name="cnpj" placeholder="00.000.000/0000-00" required/></label><label>Segmento<input name="segment" placeholder="Construção, indústria, saúde..."/></label><label>Cidade / UF<input name="city" required/></label><div className="client-form-divider"><Building2/> Usuário responsável pelo cliente</div><label>Nome completo<input name="userName" required/></label><label>E-mail de acesso<input name="email" type="email" required/></label><label>Senha inicial<input name="password" type="password" minLength={8} required/></label><label>Perfil<select name="role"><option>Gestor SSMA</option><option>Auditor</option><option>Responsável de obra</option><option>Consulta</option></select></label>{message&&<div className="client-manager-message">{message}</div>}<footer><button type="button" onClick={()=>setManager(false)}>Cancelar</button><button className="button"><Plus size={16}/> Cadastrar cliente e acesso</button></footer></form></section></div>}</div>
}
